[book]
title = "Fun Geometry"
authors = ["jonesangga"]
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[output.html]
no-section-label = true
git-repository-url = "https://github.com/jonesangga/fungeo-doc"

# Enable only in prod.
[output.html.search]
enable = true

# Enable only in prod.
[output.html.print]
enable = true           # include support for printable output
page-break = true       # insert page-break after each chapter
